# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77a42fe58cbd7fd386531d84054573e33cb984e31b4b1cea2a2f019458d793d8d3f67e5db720609c419b5f5d3330daddfc8e53f81cbcacdcf1a7c4ec73d38861

test:
  secret_key_base: 1e0218277a03d1365a756a762988873268aeea7bf1ed97363ee864a010d6a95ef25088a371afa88d2f0f7a814f9f73a407e8311ce6cf489cd080df7bbcb94165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
